version: '3.0'
services:
  postgres:
    image: postgres
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: passworddb
      POSTGRES_DB: example_db


#  SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/example_db
#  SPRING_DATASOURCE_USERNAME=userdb
#  SPRING_DATASOURCE_PASSWORD=passworddb
  service:
    image: anshemonaev/fsi:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/example_db
      SPRING_DATASOURCE_USERNAME: userdb
      SPRING_DATASOURCE_PASSWORD: passworddb
    ports:
      - "8080:8080"
    depends_on:
      - postgres
